-- ==========================================================================
-- LOCALPRINT — SEED DATA
-- Mirrors the mock PRINTERS objects already in search.html / profile.html,
-- so you can point the frontend at real D1 queries and see the same data.
-- Apply with:
--   wrangler d1 execute localprint --file=./seed.sql --local   (local test)
--   wrangler d1 execute localprint --file=./seed.sql           (remote)
-- ==========================================================================

-- --------------------------------------------------------------------------
-- Materials lookup — seed once, printers reference these via printer_materials
-- --------------------------------------------------------------------------
INSERT INTO materials (name) VALUES
  ('PLA'), ('PETG'), ('ABS'), ('TPU'), ('Resin'), ('Nylon');

-- --------------------------------------------------------------------------
-- Users — one per printer owner. password_hash values below are placeholders
-- ("changeme") — replace with real hashes generated by your signup flow.
-- --------------------------------------------------------------------------
INSERT INTO users (id, email, password_hash, email_verified) VALUES
  (1, 'owen@example.com',        'changeme', 1),
  (2, 'chen@example.com',        'changeme', 1),
  (3, 'spoolshed@example.com',   'changeme', 1),
  (4, 'resinrust@example.com',   'changeme', 1),
  (5, 'milton.makers@example.com','changeme', 1);

-- --------------------------------------------------------------------------
-- Printers
-- --------------------------------------------------------------------------
INSERT INTO printers (
  id, user_id, alias, suburb, lat, lng,
  printer_model, build_x_mm, build_y_mm, build_z_mm, 
  about,
  contact_email, accepts_submissions, offers_custom_design
) VALUES
  (1, 1, "Owen's Garage Print Co.", 'West End', -27.4820, 153.0100,
   'Bambu Lab P1S', 256, 256, 256,
   'Been printing for about four years, started with props and now do a mix of functional parts, prototypes and small batch runs. Happy to look at STL files and quote before you commit.',
   'owen@example.com', 1, 1),

  (2, 2, 'M. Chen - Prototyping', 'South Brisbane', -27.4770, 153.0190,
   'Prusa MK4', 250, 210, 220,
   'Mechanical engineer, mostly print jigs, brackets and prototypes for other makers and small businesses. Good tolerances, will flag anything that looks like it will not print well.',
   'chen@example.com', 1, 1),

  (3, 3, 'The Spool Shed', 'Highgate Hill', -27.4880, 153.0140,
   'Creality K1 Max', 300, 300, 300,
   'Large-format printer, good for bigger single pieces or batches of smaller ones. Currently a bit backed up so turnaround runs longer than usual.',
   'spoolshed@example.com', 1, 0),

  (4, 4, 'Resin & Rust', 'Woolloongabba', -27.4890, 153.0360,
   'Elegoo Saturn (Resin)', 192, 120, 200,
   'Specialise in high-detail resin prints — miniatures, jewellery casting masters, figurines. Not set up for large or structural parts.',
   'resinrust@example.com', 1, 1),

  (5, 5, 'Milton Makerspace', 'Milton', -27.4680, 152.9990,
   'Bambu Lab X1C', 256, 256, 256,
   'Community makerspace machine — a small material fee applies and jobs queue behind member projects, but it is a reliable option if you are not in a rush.',
   'milton.makers@example.com', 1, 0);

-- --------------------------------------------------------------------------
-- Printer materials (many-to-many)
-- --------------------------------------------------------------------------
INSERT INTO printer_materials (printer_id, material_id)
SELECT 1, id FROM materials WHERE name IN ('PLA','PETG','TPU');
INSERT INTO printer_materials (printer_id, material_id)
SELECT 2, id FROM materials WHERE name IN ('PLA','ABS');
INSERT INTO printer_materials (printer_id, material_id)
SELECT 3, id FROM materials WHERE name IN ('PLA','PETG');
INSERT INTO printer_materials (printer_id, material_id)
SELECT 4, id FROM materials WHERE name IN ('Resin');
INSERT INTO printer_materials (printer_id, material_id)
SELECT 5, id FROM materials WHERE name IN ('PLA','PETG','Nylon');

-- --------------------------------------------------------------------------
-- Catalogue items — only for printers that offer "print from catalogue"
-- (an empty set for a printer means that service is off, as in the frontend)
-- --------------------------------------------------------------------------
INSERT INTO catalogue_items (printer_id, name, url, sort_order) VALUES
  (1, 'Phone stand (adjustable)',      '#', 0),
  (1, 'Cable clip 6-pack',             '#', 1),
  (1, 'Desk cord organiser',           '#', 2),
  (1, 'Articulated fidget dragon',     '#', 3),
  (3, 'Large planter (200mm)',         '#', 0),
  (3, 'Storage bin set',               '#', 1),
  (4, 'D&D miniature — 32mm scale',    '#', 0);
-- Printers 2 and 5 offer no catalogue items (submissions/custom-design only),
-- matching the "hide catalogue section" behaviour already built into profile.html.
